### PR TITLE
WIP: FreeBSD support

### PR DESCRIPTION
**Pull request by bbriggs**
- [x] Add FreeBSD to metadata.json
- [x] Passes spec tests when run against FreeBSD
- [ ] Find solution for managing passwords

This PR also uses rspec-puppet-facts to test against all supported operating systems in a consistent fashion.

### CODE REVIEW

**Comment by bbriggs** [comment]
Links #49

**Comment by bbriggs** [comment]
Something funky is happening here. It passes spec tests on my machine, failing on Travis.

**Comment by bbriggs** [comment]
```
  on freebsd-10-amd64
    using minimum params
      should contain User[rnelson0] with comment => "rnelson0", shell => "/bin/bash", home => "/home/rnelson0", groups => ["group1", "group2"] and password_max_age => 90
      should not contain Group[rnelson0]
      should contain Exec[set rnelson0's password]
    managing all groups
      should contain User[rnelson0] with comment => "Rob Nelson" and groups => ["group1", "group2"]
      should contain Group[rnelson0]
      should contain Group[group1]
      should contain Group[group2]
    managing gid only
      should contain User[rnelson0] with comment => "Rob Nelson" and groups => ["group1", "group2"]
      should contain Group[rnelson0]
      should not contain Group[group1]
      should not contain Group[group2]
    set manage_groups to false
      should contain User[rnelson0] with comment => "rnelson0", groups => ["group1", "group2"] and password_max_age => 90
      should not contain Group[rnelson0]
      should not contain Group[group1]
      should not contain Group[group2]
    manage_groups with invalid input
      should raise Puppet::Error
    using full params
      should contain User[rnelson0] with comment => "Rob Nelson", shell => "/bin/zsh", home => "/nfshome/rnelson0", groups => ["group1", "group2"], password_max_age => 120 and uid => 101
      should contain Local_user::Ssh_authorized_keys[ssh-rsa AAAA...zwE1 rsa-key-20141029]
      should not contain Group[rnelson0]
    with a valid date for last_change
      should contain User[rnelson0]
      should not contain Group[rnelson0]
    with an invalid date for last_change
      should raise Puppet::Error
```

**Comment by bbriggs** [comment]
```
Finished in 3.48 seconds (files took 2.34 seconds to load)
198 examples, 0 failures
```

**Comment by rnelson0** [comment]
There are no additional conditions in the `case $::osfamily` selector for FreeBSD and Windows. Even if there's no `$action` to take for FreeBSD yet, it will still need a value.

**Comment by rnelson0** [comment]
@bbriggs any update on this one?

**Comment by bbriggs** [comment]
I forgot I was working on this. I'll get back to it and let you know my progress.

**Pull request closed without merging**
