### PR TITLE
Add support for using GID parameter in local_user type

### PR DESCRIPTION
**Pull request by bbriggs**
Allows users to specify a primary group for user other than the user's name. Defaults to name of resource.

### CODE REVIEW

**Comment by rnelson0** [comment]
Update the sample in `README.md` and I'll merge this! Same applies to #18.

**Comment by rnelson0** [comment]
Can you squash this down? git rebase -i origin/master, and choose squash for the 2nd and 3rd commits, then consolidate the commit message.

**Comment by bbriggs** [comment]
A rebase makes git think my local branch is behind this remote. Do I need to rebase and then use the Force?

**Comment by rnelson0** [comment]
Try a Git fetch origin first.

On Monday, December 21, 2015, Bren Briggs <notifications@github.com> wrote:

> A rebase makes git think my local branch is behind this remote. Do I need
> to rebase and then use the Force?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rnelson0/puppet-local_user/pull/16#issuecomment-166449077>
> .
>


-- 

Rob Nelson
rnelson0@gmail.com

**Comment by rnelson0** [comment]
Thanks @bbriggs!

**Pull request merged**
